gui:
    initial_size: [800, 600] # Use fractions in decimal form to set the window size as a fraction of the screen size (default: [800, 600])
    initial_position: [-1, -1] # Use -1 to center the window on that axis or a fraction to set that axis as a fraction of the screen size (default: [-1, -1])
    maximized: false # Options: true, false (default: false)
    full_screen: false # Options: true, false (default: false)
    resizable: true # Options: true, false (default: true)
